# 9. 데이터 선택 (조건)
조건에 해당하는 데이터 선택

In [1]:
import pandas as pd
df = pd.read_excel('score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [2]:
df['키']>=185 # 학생들의 키가 185 이상인지 여부를 나타내는 True/false

지원번호
1번     True
2번    False
3번    False
4번     True
5번     True
6번     True
7번     True
8번     True
Name: 키, dtype: bool

In [6]:
filt = (df['키']>=185)
df[filt]

       이름   학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85  Python
4번    서태웅  북산고  187   40   60   70  75  80     NaN
5번    강백호  북산고  188   15   20   10  35  10     NaN
6번    변덕규  능남고  202   80  100   95  85  80       C
7번    황태산  능남고  188   55   65   45  40  35  PYTHON
8번    윤대협  능남고  190  100   85   90  95  95      C#

In [7]:
df[~filt] # filter 를 역으로 적용하기 185 보다 키가 작은 row

       이름   학교    키  국어  영어  수학  과학  사회        SW특기
지원번호
2번    정대만  북산고  184  40  35  50  55  25        Java
3번    송태섭  북산고  168  80  75  70  80  75  Javascript

In [12]:
df.loc[df['키']>=185, ['이름', '수학', '과학']]

       이름   수학  과학
지원번호
1번    채치수  100  95
4번    서태웅   70  75
5번    강백호   10  35
6번    변덕규   95  85
7번    황태산   45  40
8번    윤대협   90  95

### 다양한 조건
& 그리고

In [22]:
df.loc[(df['키'] >= 185) & (df['학교'] == '북산고')] #키가 185 이상인 북산고 학생 데이터

       이름   학교    키  국어  영어   수학  과학  사회    SW특기
지원번호
1번    채치수  북산고  197  90  85  100  95  85  Python
4번    서태웅  북산고  187  40  60   70  75  80     NaN
5번    강백호  북산고  188  15  20   10  35  10     NaN

In [19]:
filt1 = df['학교'] == '북산고' # 이것을 logical indexing 이라고 한다.
filt1

지원번호
1번     True
2번     True
3번     True
4번     True
5번     True
6번    False
7번    False
8번    False
Name: 학교, dtype: bool

### | 또는

In [24]:
df.loc[(df['키'] < 170) | (df['키'] > 200)]

       이름   학교    키  국어   영어  수학  과학  사회        SW특기
지원번호
3번    송태섭  북산고  168  80   75  70  80  75  Javascript
6번    변덕규  능남고  202  80  100  95  85  80           C