# 5. 데이터 확인

In [1]:
import pandas as pd
df = pd.read_excel('score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

## DataFrame 확인
m

In [3]:
df.describe() # 계산을 할수있는데이터에 대해서 컬럼별로 데이터 갯수, 평균, 표준편차, 최소/최대값 등의 정보를 보여준다.

                키          국어          영어          수학         과학         사회
count    8.000000    8.000000    8.000000    8.000000   8.000000   8.000000
mean   188.000000   62.500000   65.625000   66.250000  70.000000  60.625000
std      9.985704   29.519969   26.917533   30.325614  23.754699  32.120032
min    168.000000   15.000000   20.000000   10.000000  35.000000  10.000000
25%    186.250000   40.000000   53.750000   48.750000  51.250000  32.500000
50%    188.000000   67.500000   70.000000   70.000000  77.500000  77.500000
75%    191.750000   82.500000   85.000000   91.250000  87.500000  81.250000
max    202.000000  100.000000  100.000000  100.000000  95.000000  95.000000

In [4]:
df.info()

<class 'pandas.DataFrame'>
Index: 8 entries, 1번 to 8번
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      8 non-null      str
 1   학교      8 non-null      str
 2   키       8 non-null      int64
 3   국어      8 non-null      int64
 4   영어      8 non-null      int64
 5   수학      8 non-null      int64
 6   과학      8 non-null      int64
 7   사회      8 non-null      int64
 8   SW특기    6 non-null      str
dtypes: int64(6), str(3)
memory usage: 640.0+ bytes

In [5]:
df.head() # 처음 5개의 row 를 가져옴

       이름   학교    키  국어  영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197  90  85  100  95  85      Python
2번    정대만  북산고  184  40  35   50  55  25        Java
3번    송태섭  북산고  168  80  75   70  80  75  Javascript
4번    서태웅  북산고  187  40  60   70  75  80         NaN
5번    강백호  북산고  188  15  20   10  35  10         NaN

In [6]:
df.head(7) #처음 7개의 row 를 가져옴

       이름   학교    키  국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197  90   85  100  95  85      Python
2번    정대만  북산고  184  40   35   50  55  25        Java
3번    송태섭  북산고  168  80   75   70  80  75  Javascript
4번    서태웅  북산고  187  40   60   70  75  80         NaN
5번    강백호  북산고  188  15   20   10  35  10         NaN
6번    변덕규  능남고  202  80  100   95  85  80           C
7번    황태산  능남고  188  55   65   45  40  35      PYTHON

In [7]:
df.tail() # 마지막  5개 (default=5)

       이름   학교    키   국어   영어  수학  과학  사회    SW특기
지원번호
4번    서태웅  북산고  187   40   60  70  75  80     NaN
5번    강백호  북산고  188   15   20  10  35  10     NaN
6번    변덕규  능남고  202   80  100  95  85  80       C
7번    황태산  능남고  188   55   65  45  40  35  PYTHON
8번    윤대협  능남고  190  100   85  90  95  95      C#

In [8]:
df.tail(3) # 마지막 3개

       이름   학교    키   국어   영어  수학  과학  사회    SW특기
지원번호
6번    변덕규  능남고  202   80  100  95  85  80       C
7번    황태산  능남고  188   55   65  45  40  35  PYTHON
8번    윤대협  능남고  190  100   85  90  95  95      C#

In [9]:
df.values #2차원 리스트의 형태로 나오게 된다.

array([['채치수', '북산고', 197, 90, 85, 100, 95, 85, 'Python'],
       ['정대만', '북산고', 184, 40, 35, 50, 55, 25, 'Java'],
       ['송태섭', '북산고', 168, 80, 75, 70, 80, 75, 'Javascript'],
       ['서태웅', '북산고', 187, 40, 60, 70, 75, 80, nan],
       ['강백호', '북산고', 188, 15, 20, 10, 35, 10, nan],
       ['변덕규', '능남고', 202, 80, 100, 95, 85, 80, 'C'],
       ['황태산', '능남고', 188, 55, 65, 45, 40, 35, 'PYTHON'],
       ['윤대협', '능남고', 190, 100, 85, 90, 95, 95, 'C#']], dtype=object)

In [10]:
df.index # dataFrame 의 index 정보, 어떤 값을 가지고 있는지, 타입

Index(['1번', '2번', '3번', '4번', '5번', '6번', '7번', '8번'], dtype='str', name='지원번호')

In [13]:
df.columns # column 의 정보, 어떤 값을 가지고 있는지, 타입

Index(['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기'], dtype='str')

In [14]:
df.shape # row, column

(8, 9)

In [16]:
## Series 확인 하나의 컬럼
df['키'].describe()

count      8.000000
mean     188.000000
std        9.985704
min      168.000000
25%      186.250000
50%      188.000000
75%      191.750000
max      202.000000
Name: 키, dtype: float64

In [17]:
df['키'].min()

np.int64(168)

In [18]:
df['키'].max()

np.int64(202)

In [19]:
df['키'].nlargest(3) # 키 큰 사람 순서대로 3명 데이터

지원번호
6번    202
1번    197
8번    190
Name: 키, dtype: int64

In [20]:
df['키'].mean() # 평균을 구하는 메서드

np.float64(188.0)

In [21]:
df['키'].sum() # 전체 시리즈의 총합

np.int64(1504)

In [25]:
df['SW특기'].count() # NaN 데이터를 제외한 컬럼의 총합

np.int64(6)

In [26]:
df['학교'].unique() # 중복을 제외하고, sql 에서 distinct 같은거

<StringArray>
['북산고', '능남고']
Length: 2, dtype: str

In [27]:
df['학교'].nunique() # 중복을 제외하고 학교가 몇개있는지

2