# 11. 데이터 정렬

In [3]:
import pandas as pd
df = pd.read_excel('score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [4]:
df.sort_values('키') # 키 기준으로 오름차순 정렬

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
2번    정대만  북산고  184   40   35   50  55  25        Java
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#
1번    채치수  북산고  197   90   85  100  95  85      Python
6번    변덕규  능남고  202   80  100   95  85  80           C

In [5]:
df.sort_values('키', ascending=False) # 키 기준으로 내림차순 정렬

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
6번    변덕규  능남고  202   80  100   95  85  80           C
1번    채치수  북산고  197   90   85  100  95  85      Python
8번    윤대협  능남고  190  100   85   90  95  95          C#
5번    강백호  북산고  188   15   20   10  35  10         NaN
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
4번    서태웅  북산고  187   40   60   70  75  80         NaN
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript

In [6]:
df.sort_values(['수학', '영어'], ascending=False)  # 1. 수학기준 내림차순 2. 영어 기준 내림차순 (만약 수학과 영어가 같은경우 영어 내림차순)

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
6번    변덕규  능남고  202   80  100   95  85  80           C
8번    윤대협  능남고  190  100   85   90  95  95          C#
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
2번    정대만  북산고  184   40   35   50  55  25        Java
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
5번    강백호  북산고  188   15   20   10  35  10         NaN

In [7]:
df.sort_values(['수학', '영어'])

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
5번    강백호  북산고  188   15   20   10  35  10         NaN
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
2번    정대만  북산고  184   40   35   50  55  25        Java
4번    서태웅  북산고  187   40   60   70  75  80         NaN
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
8번    윤대협  능남고  190  100   85   90  95  95          C#
6번    변덕규  능남고  202   80  100   95  85  80           C
1번    채치수  북산고  197   90   85  100  95  85      Python

In [8]:
df.sort_values(['수학', '영어'], ascending=[True, False])

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
5번    강백호  북산고  188   15   20   10  35  10         NaN
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
8번    윤대협  능남고  190  100   85   90  95  95          C#
6번    변덕규  능남고  202   80  100   95  85  80           C
1번    채치수  북산고  197   90   85  100  95  85      Python

In [9]:
df['키'].sort_values() # 키 데이터를 가지고 옴(series) 에 대해서 오름차순 정렬

지원번호
3번    168
2번    184
4번    187
5번    188
7번    188
8번    190
1번    197
6번    202
Name: 키, dtype: int64

In [10]:
df.sort_index()

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#