# 10. 결측치
비어 있는 데이터

In [59]:
import pandas as pd
df = pd.read_excel('score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

## 데이터 채우기  fillna

In [39]:
df.fillna('') # NaN 데이터를 빈 칸으로 채움

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80
5번    강백호  북산고  188   15   20   10  35  10
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [40]:
df.fillna('없음') # 데이터에 있는 모든 nan 값을 없음 으로 채우기

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80          없음
5번    강백호  북산고  188   15   20   10  35  10          없음
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [53]:
df
import numpy as np
df['학교'] = np.nan # 학교 데이터 전체를 NaN 으로 채움
df

       이름  학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수 NaN  197   90   85  100  95  85      Python
2번    정대만 NaN  184   40   35   50  55  25        Java
3번    송태섭 NaN  168   80   75   70  80  75  Javascript
4번    서태웅 NaN  187   40   60   70  75  80         NaN
5번    강백호 NaN  188   15   20   10  35  10         NaN
6번    변덕규 NaN  202   80  100   95  85  80           C
7번    황태산 NaN  188   55   65   45  40  35      PYTHON
8번    윤대협 NaN  190  100   85   90  95  95          C#

In [61]:
df['SW특기'] = df['SW특기'].fillna('확인 중') # 복사한것을 수정한것을 할당하는 형식으로 쓰는것이 안전하다.

## 데이터 제외하기 dropna

In [66]:
import pandas as pd
df = pd.read_excel('score.xlsx', index_col='지원번호')

In [65]:
df.dropna(inplace=True) # nan 가 존재하는 행은 무조건 삭제
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

* axis : index or column 열을 지울것인가, 컬럼을 지울것인가.
* how : any or all 하나라도 있으면, 모두가 NaN 일때.

In [67]:
df.dropna(axis='index', how='any')

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#