# 6. 데이터 선택

In [1]:
import pandas as pd
df = pd.read_excel('score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

## Column 선택(label)

In [9]:
df['이름']

지원번호
1번    채치수
2번    정대만
3번    송태섭
4번    서태웅
5번    강백호
6번    변덕규
7번    황태산
8번    윤대협
Name: 이름, dtype: str

In [5]:
df[['이름','키']]

       이름    키
지원번호
1번    채치수  197
2번    정대만  184
3번    송태섭  168
4번    서태웅  187
5번    강백호  188
6번    변덕규  202
7번    황태산  188
8번    윤대협  190

## Column 선택(정수 인덱스)m

In [6]:
df.columns

Index(['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기'], dtype='str')

In [7]:
df.columns[0] # index 의 0 번째 컬럼이 뭔지

'이름'

In [8]:
df[df.columns[0]] # index 의 0 번째 컬럼으로 전체 row 조회 = df['이름']

지원번호
1번    채치수
2번    정대만
3번    송태섭
4번    서태웅
5번    강백호
6번    변덕규
7번    황태산
8번    윤대협
Name: 이름, dtype: str

In [10]:
df[df.columns[-1]] # 맨 끝에있는 column

지원번호
1번        Python
2번          Java
3번    Javascript
4번           NaN
5번           NaN
6번             C
7번        PYTHON
8번            C#
Name: SW특기, dtype: str

## 슬라이싱

In [13]:
df['영어'][0:5] # 0~4 까지 영어 점수 데이터 가지고 오기

지원번호
1번    85
2번    35
3번    75
4번    60
5번    20
Name: 영어, dtype: int64

In [14]:
df[['이름', '키']][:3] # 처음 3명의 이름, 키 정보를 가지고 온다

       이름    키
지원번호
1번    채치수  197
2번    정대만  184
3번    송태섭  168