# 12. 데이터 수정

In [61]:
import pandas as pd
df = pd.read_excel('score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

## Column 수정 (약간 쿼리에서 update 문인가?)

In [78]:
df['학교'].replace({'북산고': '상북고', '능남고': '무슨고'}) # 딕셔너리 형태로 바꾸고자 하는 행과 바꾸려고 하는 값 넣어주기

지원번호
1번       상북고
2번       상북고
3번       상북고
4번       상북고
5번       상북고
6번       무슨고
7번       무슨고
8번       무슨고
9번    해남고등학교
Name: 학교, dtype: str

In [79]:
df['학교'] = df['학교'].replace({'북산고': '상북고'}) # 딕셔너리 형태로 바꾸고자 하는 행과 바꾸려고 하는 값 넣어주기 inplace 사용하지 말기.
df

       이름      학교    키   국어   영어   수학  과학  사회        SW특기   총합    결과
지원번호
1번    채치수     상북고  197   90   85  100  95  85      Python  455  Pass
2번    정대만     상북고  184   40   35   50  55  25        Java  205  Fail
3번    송태섭     상북고  168   80   75   70  80  75  Javascript  380  Fail
4번    서태웅     상북고  187   40   60   70  75  80         NaN  325  Fail
5번    강백호     상북고  188   15   20   10  35  10         NaN   90  Fail
6번    변덕규     능남고  202   80  100   95  85  80           C  440  Pass
7번    황태산     능남고  188   55   65   45  40  35      PYTHON  240  Fail
8번    윤대협     능남고  190  100   85   90  95  95          C#  465  Pass
9번    이정환  해남고등학교  184   90   90   90  90  90      Kotlin  450  Pass

In [22]:
df['SW특기'] = df['SW특기'].str.lower()
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  상북고  197   90   85  100  95  85      python
2번    정대만  상북고  184   40   35   50  55  25        java
3번    송태섭  상북고  168   80   75   70  80  75  javascript
4번    서태웅  상북고  187   40   60   70  75  80         NaN
5번    강백호  상북고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           c
7번    황태산  능남고  188   55   65   45  40  35      python
8번    윤대협  능남고  190  100   85   90  95  95          c#

In [27]:
df['SW특기'] = df['SW특기'].str.upper()
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  상북고  197   90   85  100  95  85      PYTHON
2번    정대만  상북고  184   40   35   50  55  25        JAVA
3번    송태섭  상북고  168   80   75   70  80  75  JAVASCRIPT
4번    서태웅  상북고  187   40   60   70  75  80         NaN
5번    강백호  상북고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [80]:
df['학교'] = df['학교'] + '등학교' # 학교 데이터 + 등학교
df

       이름         학교    키   국어   영어   수학  과학  사회        SW특기   총합    결과
지원번호
1번    채치수     상북고등학교  197   90   85  100  95  85      Python  455  Pass
2번    정대만     상북고등학교  184   40   35   50  55  25        Java  205  Fail
3번    송태섭     상북고등학교  168   80   75   70  80  75  Javascript  380  Fail
4번    서태웅     상북고등학교  187   40   60   70  75  80         NaN  325  Fail
5번    강백호     상북고등학교  188   15   20   10  35  10         NaN   90  Fail
6번    변덕규     능남고등학교  202   80  100   95  85  80           C  440  Pass
7번    황태산     능남고등학교  188   55   65   45  40  35      PYTHON  240  Fail
8번    윤대협     능남고등학교  190  100   85   90  95  95          C#  465  Pass
9번    이정환  해남고등학교등학교  184   90   90   90  90  90      Kotlin  450  Pass

## Column 추가

In [72]:
df['총합'] = df['국어']+df['영어']+df['수학']+df['과학']+df['사회']

In [73]:
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기   총합
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python  455
2번    정대만  북산고  184   40   35   50  55  25        Java  205
3번    송태섭  북산고  168   80   75   70  80  75  Javascript  380
4번    서태웅  북산고  187   40   60   70  75  80         NaN  325
5번    강백호  북산고  188   15   20   10  35  10         NaN   90
6번    변덕규  능남고  202   80  100   95  85  80           C  440
7번    황태산  능남고  188   55   65   45  40  35      PYTHON  240
8번    윤대협  능남고  190  100   85   90  95  95          C#  465

In [74]:
df['결과'] = 'Fail' # 결과 Column 을 추가하고 전체 데이터는 Fail 로 초기화
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기   총합    결과
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python  455  Fail
2번    정대만  북산고  184   40   35   50  55  25        Java  205  Fail
3번    송태섭  북산고  168   80   75   70  80  75  Javascript  380  Fail
4번    서태웅  북산고  187   40   60   70  75  80         NaN  325  Fail
5번    강백호  북산고  188   15   20   10  35  10         NaN   90  Fail
6번    변덕규  능남고  202   80  100   95  85  80           C  440  Fail
7번    황태산  능남고  188   55   65   45  40  35      PYTHON  240  Fail
8번    윤대협  능남고  190  100   85   90  95  95          C#  465  Fail

In [33]:
df.loc['1번']

이름         채치수
학교      상북고등학교
키          197
국어          90
영어          85
수학         100
과학          95
사회          85
SW특기    PYTHON
총합         455
결과        Fail
Name: 1번, dtype: object

In [75]:
df.loc[df['총합'] > 400 ,'결과'] = 'Pass' # loc[row , col]
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기   총합    결과
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python  455  Pass
2번    정대만  북산고  184   40   35   50  55  25        Java  205  Fail
3번    송태섭  북산고  168   80   75   70  80  75  Javascript  380  Fail
4번    서태웅  북산고  187   40   60   70  75  80         NaN  325  Fail
5번    강백호  북산고  188   15   20   10  35  10         NaN   90  Fail
6번    변덕규  능남고  202   80  100   95  85  80           C  440  Pass
7번    황태산  능남고  188   55   65   45  40  35      PYTHON  240  Fail
8번    윤대협  능남고  190  100   85   90  95  95          C#  465  Pass

## Column 삭제

In [48]:
df.drop(columns=['총합']) # 총합 Column 삭제하기

       이름      학교    키  과학  사회        SW특기    결과
지원번호
1번    채치수  상북고등학교  197  95  85      PYTHON  Pass
2번    정대만  상북고등학교  184  55  25        JAVA  Fail
3번    송태섭  상북고등학교  168  80  75  JAVASCRIPT  Fail
4번    서태웅  상북고등학교  187  75  80         NaN  Fail
5번    강백호  상북고등학교  188  35  10         NaN  Fail
6번    변덕규  능남고등학교  202  85  80           C  Pass
7번    황태산  능남고등학교  188  40  35      PYTHON  Fail
8번    윤대협  능남고등학교  190  95  95          C#  Pass

In [53]:
df.drop(columns=['국어', '영어', '수학'], inplace= True) # 국어, 영어, 수학 column 을 삭제 (이건 인플레이스 해도 됨)
df

       이름   학교    키  과학  사회        SW특기
지원번호
1번    채치수  북산고  197  95  85      Python
2번    정대만  북산고  184  55  25        Java
3번    송태섭  북산고  168  80  75  Javascript
4번    서태웅  북산고  187  75  80         NaN
5번    강백호  북산고  188  35  10         NaN
6번    변덕규  능남고  202  85  80           C
7번    황태산  능남고  188  40  35      PYTHON
8번    윤대협  능남고  190  95  95          C#

## Row 삭제

In [58]:
df.drop(index='4번') # 4번 학생 데이터 row 삭제

       이름   학교    키  과학  사회        SW특기
지원번호
1번    채치수  북산고  197  95  85      Python
2번    정대만  북산고  184  55  25        Java
3번    송태섭  북산고  168  80  75  Javascript
5번    강백호  북산고  188  35  10         NaN
6번    변덕규  능남고  202  85  80           C
7번    황태산  능남고  188  40  35      PYTHON
8번    윤대협  능남고  190  95  95          C#

In [64]:
filt = df['수학'] < 80 # 수학 점수 80 점 미만 학생 필터링
filt
df[filt]

       이름   학교    키  국어  영어  수학  과학  사회        SW특기
지원번호
2번    정대만  북산고  184  40  35  50  55  25        Java
3번    송태섭  북산고  168  80  75  70  80  75  Javascript
4번    서태웅  북산고  187  40  60  70  75  80         NaN
5번    강백호  북산고  188  15  20  10  35  10         NaN
7번    황태산  능남고  188  55  65  45  40  35      PYTHON

In [65]:
df[filt].index # logical index 에서 걸러진 나머지 인덱스들이 나온다.

Index(['2번', '3번', '4번', '5번', '7번'], dtype='str', name='지원번호')

In [66]:
df.drop(index=df[filt].index)

       이름   학교    키   국어   영어   수학  과학  사회    SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85  Python
6번    변덕규  능남고  202   80  100   95  85  80       C
8번    윤대협  능남고  190  100   85   90  95  95      C#

## Row 추가

In [81]:
df.loc['9번'] = ['이정환', '해남고등학교', 184, 90, 90, 90, 90,90, 'Kotlin', 450, 'Pass']
df

       이름      학교    키   국어   영어   수학  과학  사회        SW특기   총합    결과
지원번호
1번    채치수  상북고등학교  197   90   85  100  95  85      Python  455  Pass
2번    정대만  상북고등학교  184   40   35   50  55  25        Java  205  Fail
3번    송태섭  상북고등학교  168   80   75   70  80  75  Javascript  380  Fail
4번    서태웅  상북고등학교  187   40   60   70  75  80         NaN  325  Fail
5번    강백호  상북고등학교  188   15   20   10  35  10         NaN   90  Fail
6번    변덕규  능남고등학교  202   80  100   95  85  80           C  440  Pass
7번    황태산  능남고등학교  188   55   65   45  40  35      PYTHON  240  Fail
8번    윤대협  능남고등학교  190  100   85   90  95  95          C#  465  Pass
9번    이정환  해남고등학교  184   90   90   90  90  90      Kotlin  450  Pass

## Cell 수정

In [83]:
df.loc['4번', 'SW특기'] = 'python'
df

       이름      학교    키   국어   영어   수학  과학  사회        SW특기   총합    결과
지원번호
1번    채치수  상북고등학교  197   90   85  100  95  85      Python  455  Pass
2번    정대만  상북고등학교  184   40   35   50  55  25        Java  205  Fail
3번    송태섭  상북고등학교  168   80   75   70  80  75  Javascript  380  Fail
4번    서태웅  상북고등학교  187   40   60   70  75  80      python  325  Fail
5번    강백호  상북고등학교  188   15   20   10  35  10         NaN   90  Fail
6번    변덕규  능남고등학교  202   80  100   95  85  80           C  440  Pass
7번    황태산  능남고등학교  188   55   65   45  40  35      PYTHON  240  Fail
8번    윤대협  능남고등학교  190  100   85   90  95  95          C#  465  Pass
9번    이정환  해남고등학교  184   90   90   90  90  90      Kotlin  450  Pass

In [86]:
df.loc['5번', ['학교', 'SW특기']] = ['능남고등학교', 'C']
df

       이름      학교    키   국어   영어   수학  과학  사회        SW특기   총합    결과
지원번호
1번    채치수  상북고등학교  197   90   85  100  95  85      Python  455  Pass
2번    정대만  상북고등학교  184   40   35   50  55  25        Java  205  Fail
3번    송태섭  상북고등학교  168   80   75   70  80  75  Javascript  380  Fail
4번    서태웅  상북고등학교  187   40   60   70  75  80      python  325  Fail
5번    강백호  능남고등학교  188   15   20   10  35  10           C   90  Fail
6번    변덕규  능남고등학교  202   80  100   95  85  80           C  440  Pass
7번    황태산  능남고등학교  188   55   65   45  40  35      PYTHON  240  Fail
8번    윤대협  능남고등학교  190  100   85   90  95  95          C#  465  Pass
9번    이정환  해남고등학교  184   90   90   90  90  90      Kotlin  450  Pass

## Column 순서 변경하기

In [87]:
cols = list(df.columns)
cols

['이름', '학교', '키', '국어', '영어', '수학', '과학', '사회', 'SW특기', '총합', '결과']

In [98]:
d = [cols[-1]] + cols[0:-1] # 결과를 맨 앞으로 가지고 오기
d
df = df[d]
df

        결과   이름      학교    키   국어   영어   수학  과학  사회        SW특기   총합
지원번호
1번    Pass  채치수  상북고등학교  197   90   85  100  95  85      Python  455
2번    Fail  정대만  상북고등학교  184   40   35   50  55  25        Java  205
3번    Fail  송태섭  상북고등학교  168   80   75   70  80  75  Javascript  380
4번    Fail  서태웅  상북고등학교  187   40   60   70  75  80      python  325
5번    Fail  강백호  능남고등학교  188   15   20   10  35  10           C   90
6번    Pass  변덕규  능남고등학교  202   80  100   95  85  80           C  440
7번    Fail  황태산  능남고등학교  188   55   65   45  40  35      PYTHON  240
8번    Pass  윤대협  능남고등학교  190  100   85   90  95  95          C#  465
9번    Pass  이정환  해남고등학교  184   90   90   90  90  90      Kotlin  450

In [100]:
df = df[['결과', '이름', '학교']]
df

        결과   이름      학교
지원번호
1번    Pass  채치수  상북고등학교
2번    Fail  정대만  상북고등학교
3번    Fail  송태섭  상북고등학교
4번    Fail  서태웅  상북고등학교
5번    Fail  강백호  능남고등학교
6번    Pass  변덕규  능남고등학교
7번    Fail  황태산  능남고등학교
8번    Pass  윤대협  능남고등학교
9번    Pass  이정환  해남고등학교

In [103]:
df.columns = ['Result', 'Name', 'School']
df

     Result Name  School
지원번호
1번     Pass  채치수  상북고등학교
2번     Fail  정대만  상북고등학교
3번     Fail  송태섭  상북고등학교
4번     Fail  서태웅  상북고등학교
5번     Fail  강백호  능남고등학교
6번     Pass  변덕규  능남고등학교
7번     Fail  황태산  능남고등학교
8번     Pass  윤대협  능남고등학교
9번     Pass  이정환  해남고등학교