# 4. 파일 저장 및 열기
DataFrame 객체를 excel, csv, txt 등 형태의 파일로 저장 및 열기

In [1]:
import pandas as pd
data = {
    '이름': ['채치수', '정대만', '송태섭', '서태웅', '강백호', '변덕규', '황태산', '윤대협'],
    '학교': ['북산고', '북산고', '북산고', '북산고', '북산고', '능남고', '능남고', '능남고'],
    '키': [197, 184, 168, 187, 188, 202, 188, 190],
    '국어': [90, 40, 80, 40, 15, 80, 55, 100],
    '영어': [85, 35, 75, 60, 20, 100, 65, 85],
    '수학': [100, 50, 70, 70, 10, 95, 45, 90],
    '과학': [95, 55, 80, 75, 35, 85, 40, 95],
    '사회': [85, 25, 75, 80, 10, 80, 35, 95],
    'SW특기': ['Python', 'Java', 'Javascript', '', '', 'C', 'PYTHON', 'C#']
}
df = pd.DataFrame(data, index=['1번', '2번', '3번', '4번', '5번', '6번', '7번', '8번'])
df.index.name = '지원번호'
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80
5번    강백호  북산고  188   15   20   10  35  10
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

In [9]:
df.to_csv('score.csv', encoding='utf-8-sig') # excel 로 열었을때 인코딩 하는 방법

In [11]:
df.to_csv('score.csv', encoding='utf-8-sig', index=False) # 인덱스를 제외하는 방법

### 텍스트(.txt) 파일로 저장

In [12]:
df.to_csv('score.txt', sep='\t') # tab 으로 구분된 텍스트 파일 생성

### 엑셀 파일로 저장

In [17]:
df.to_excel('score.xlsx')

---
## 열기
csv 파일 열기

In [18]:
df= pd.read_csv('score.csv') # read_csv() 의 리턴값 = DataFrame 이다.
df

    이름   학교    키   국어   영어   수학  과학  사회        SW특기
0  채치수  북산고  197   90   85  100  95  85      Python
1  정대만  북산고  184   40   35   50  55  25        Java
2  송태섭  북산고  168   80   75   70  80  75  Javascript
3  서태웅  북산고  187   40   60   70  75  80         NaN
4  강백호  북산고  188   15   20   10  35  10         NaN
5  변덕규  능남고  202   80  100   95  85  80           C
6  황태산  능남고  188   55   65   45  40  35      PYTHON
7  윤대협  능남고  190  100   85   90  95  95          C#

In [21]:
df = pd.read_csv('score.csv', skiprows=1) # 무시하고 싶은 row 제외 가능
# 지정된 갯수 만큼의 row 를 건너뛴다.
# 이름 학교 키 국어 영어 수학 과학 사회 sw특기도 하나의 rows 로 간주된다.
df

   채치수  북산고  197   90   85  100  95  85.1      Python
0  정대만  북산고  184   40   35   50  55    25        Java
1  송태섭  북산고  168   80   75   70  80    75  Javascript
2  서태웅  북산고  187   40   60   70  75    80         NaN
3  강백호  북산고  188   15   20   10  35    10         NaN
4  변덕규  능남고  202   80  100   95  85    80           C
5  황태산  능남고  188   55   65   45  40    35      PYTHON
6  윤대협  능남고  190  100   85   90  95    95          C#

In [23]:
df = pd.read_csv('score.csv', skiprows=[1,3,5]) # 1,3,5 rows 제외하기
df

    이름   학교    키   국어   영어  수학  과학  사회    SW특기
0  정대만  북산고  184   40   35  50  55  25    Java
1  서태웅  북산고  187   40   60  70  75  80     NaN
2  변덕규  능남고  202   80  100  95  85  80       C
3  황태산  능남고  188   55   65  45  40  35  PYTHON
4  윤대협  능남고  190  100   85  90  95  95      C#

In [25]:
df = pd.read_csv('score.csv', nrows=4) # 지정된 갯수 만큼의 row 만 가져온다.
df

    이름   학교    키  국어  영어   수학  과학  사회        SW특기
0  채치수  북산고  197  90  85  100  95  85      Python
1  정대만  북산고  184  40  35   50  55  25        Java
2  송태섭  북산고  168  80  75   70  80  75  Javascript
3  서태웅  북산고  187  40  60   70  75  80         NaN

In [27]:
df = pd.read_csv('score.csv',skiprows=2 , nrows=4) # 앞의 2개 제외이후, 4 row 를 가지고 온다.
df

   정대만  북산고  184  40   35  50  55  25        Java
0  송태섭  북산고  168  80   75  70  80  75  Javascript
1  서태웅  북산고  187  40   60  70  75  80         NaN
2  강백호  북산고  188  15   20  10  35  10         NaN
3  변덕규  능남고  202  80  100  95  85  80           C

### 텍스트(.txt) 파일 열기

In [29]:
df = pd.read_csv('score.txt', sep='\t', index_col='지원번호') # 인덱스 설정하기
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#

### 엑셀 파일 열기

In [30]:
df =pd.read_excel('score.xlsx')
df

  지원번호   이름   학교    키   국어   영어   수학  과학  사회        SW특기
0   1번  채치수  북산고  197   90   85  100  95  85      Python
1   2번  정대만  북산고  184   40   35   50  55  25        Java
2   3번  송태섭  북산고  168   80   75   70  80  75  Javascript
3   4번  서태웅  북산고  187   40   60   70  75  80         NaN
4   5번  강백호  북산고  188   15   20   10  35  10         NaN
5   6번  변덕규  능남고  202   80  100   95  85  80           C
6   7번  황태산  능남고  188   55   65   45  40  35      PYTHON
7   8번  윤대협  능남고  190  100   85   90  95  95          C#

In [31]:
df =pd.read_excel('score.xlsx', index_col='지원번호')
df

       이름   학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    채치수  북산고  197   90   85  100  95  85      Python
2번    정대만  북산고  184   40   35   50  55  25        Java
3번    송태섭  북산고  168   80   75   70  80  75  Javascript
4번    서태웅  북산고  187   40   60   70  75  80         NaN
5번    강백호  북산고  188   15   20   10  35  10         NaN
6번    변덕규  능남고  202   80  100   95  85  80           C
7번    황태산  능남고  188   55   65   45  40  35      PYTHON
8번    윤대협  능남고  190  100   85   90  95  95          C#